#!/bin/bash

IMAGE_NAME="suidroot/chipwhisperer5"
IMAGE_SOURCE="https://github.com/suidroot/chipwhisperer5-docker.git"

if [[ "$(docker images -q $IMAGE_NAME 2> /dev/null)" == "" ]]; then
	docker build -t $IMAGE_NAME $IMAGE_SOURCE
fi


if [ -z "$1" ]
then
      echo "Please supply a token for authentication!"
      exit 1
fi

if [ -z "$2" ]
then
	echo "Please supply a directory to work in."
	exit 1
fi

docker run -i -t -p 8888:8888 --privileged \
	-u $(id -u ${USER}):$(id -g ${USER}) --group-add plugdev \
	-v /dev/bus/usb:/dev/bus/usb \
	-v ${2}:/cw_workspace \
	--env TOKEN=${1} \
	--env HOME=/home \
	-v /etc/passwd:/etc/passwd:ro \
	-v /etc/group:/etc/group:ro \
	-v /etc/group-:/etc/group-:ro \
    suidroot/chipwhisperer5	
