#!/bin/bash

SR_PATH="/root/sr"
IMAGE_NAME="suidroot/sigrock"
IMAGE_SOURCE="https://github.com/suidroot/chipwhisperer5-docker.git"

if [[ "$(docker images -q $IMAGE_NAME 2> /dev/null)" == "" ]]; then
	docker build -t $IMAGE_NAME $IMAGE_SOURCE
fi


docker run --name PulseView \
    --tty --interactive --network=host \
    --env DISPLAY=$DISPLAY \
    --volume $XAUTH:/root/.Xauthority \
    -v $HOME:/root \
    $IMAGE_NAME \
    $SR_PATH/bin/PulseView
