#!/bin/bash

DOCKERIMAGE="suidroot/sigrock"
SR_PATH="/root/sr"
IMAGE_NAME="suidroot/sigrock"
IMAGE_SOURCE="https://github.com/suidroot/chipwhisperer5-docker.git"

if [[ "$(docker images -q $IMAGE_NAME 2> /dev/null)" == "" ]]; then
	docker build -t $IMAGE_NAME $IMAGE_SOURCE
fi


docker run --name sigrok-cli \
    -v /dev/bus/usb:/dev/bus/usb \
    --privileged \
    --tty --interactive --network=host \
    -v $HOME:/root \
    $DOCKERIMAGE \
    $SR_PATH/bin/sigrok-cli
